// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: document.proto

package doc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocumentService_StreamDocument_FullMethodName  = "/document.DocumentService/StreamDocument"
	DocumentService_GetFullDocument_FullMethodName = "/document.DocumentService/GetFullDocument"
	DocumentService_StreamLogs_FullMethodName      = "/document.DocumentService/StreamLogs"
)

// DocumentServiceClient is the client API for DocumentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentServiceClient interface {
	StreamDocument(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DocumentUpdate, DocumentUpdate], error)
	GetFullDocument(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FullDocumentResponse, error)
	StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Empty, LogMessage], error)
}

type documentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentServiceClient(cc grpc.ClientConnInterface) DocumentServiceClient {
	return &documentServiceClient{cc}
}

func (c *documentServiceClient) StreamDocument(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DocumentUpdate, DocumentUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DocumentService_ServiceDesc.Streams[0], DocumentService_StreamDocument_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DocumentUpdate, DocumentUpdate]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentService_StreamDocumentClient = grpc.BidiStreamingClient[DocumentUpdate, DocumentUpdate]

func (c *documentServiceClient) GetFullDocument(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FullDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FullDocumentResponse)
	err := c.cc.Invoke(ctx, DocumentService_GetFullDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Empty, LogMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DocumentService_ServiceDesc.Streams[1], DocumentService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, LogMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentService_StreamLogsClient = grpc.BidiStreamingClient[Empty, LogMessage]

// DocumentServiceServer is the server API for DocumentService service.
// All implementations must embed UnimplementedDocumentServiceServer
// for forward compatibility.
type DocumentServiceServer interface {
	StreamDocument(grpc.BidiStreamingServer[DocumentUpdate, DocumentUpdate]) error
	GetFullDocument(context.Context, *Empty) (*FullDocumentResponse, error)
	StreamLogs(grpc.BidiStreamingServer[Empty, LogMessage]) error
	mustEmbedUnimplementedDocumentServiceServer()
}

// UnimplementedDocumentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentServiceServer struct{}

func (UnimplementedDocumentServiceServer) StreamDocument(grpc.BidiStreamingServer[DocumentUpdate, DocumentUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method StreamDocument not implemented")
}
func (UnimplementedDocumentServiceServer) GetFullDocument(context.Context, *Empty) (*FullDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFullDocument not implemented")
}
func (UnimplementedDocumentServiceServer) StreamLogs(grpc.BidiStreamingServer[Empty, LogMessage]) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedDocumentServiceServer) mustEmbedUnimplementedDocumentServiceServer() {}
func (UnimplementedDocumentServiceServer) testEmbeddedByValue()                         {}

// UnsafeDocumentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentServiceServer will
// result in compilation errors.
type UnsafeDocumentServiceServer interface {
	mustEmbedUnimplementedDocumentServiceServer()
}

func RegisterDocumentServiceServer(s grpc.ServiceRegistrar, srv DocumentServiceServer) {
	// If the following call pancis, it indicates UnimplementedDocumentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentService_ServiceDesc, srv)
}

func _DocumentService_StreamDocument_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DocumentServiceServer).StreamDocument(&grpc.GenericServerStream[DocumentUpdate, DocumentUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentService_StreamDocumentServer = grpc.BidiStreamingServer[DocumentUpdate, DocumentUpdate]

func _DocumentService_GetFullDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).GetFullDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_GetFullDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).GetFullDocument(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DocumentServiceServer).StreamLogs(&grpc.GenericServerStream[Empty, LogMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentService_StreamLogsServer = grpc.BidiStreamingServer[Empty, LogMessage]

// DocumentService_ServiceDesc is the grpc.ServiceDesc for DocumentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "document.DocumentService",
	HandlerType: (*DocumentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFullDocument",
			Handler:    _DocumentService_GetFullDocument_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamDocument",
			Handler:       _DocumentService_StreamDocument_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _DocumentService_StreamLogs_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "document.proto",
}
