# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: labyrinth.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'labyrinth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flabyrinth.proto\x12\tlabyrinth\"\x0e\n\x0c\x45mptyRequest\".\n\rLabyrinthInfo\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"t\n\x0cPlayerStatus\x12\r\n\x05score\x18\x01 \x01(\x05\x12\x0e\n\x06health\x18\x02 \x01(\x05\x12,\n\x0f\x63urrentPosition\x18\x03 \x01(\x0b\x32\x13.labyrinth.Position\x12\x17\n\x0fremainingSpells\x18\x04 \x01(\x05\" \n\x0bMoveRequest\x12\x11\n\tdirection\x18\x01 \x01(\t\"\x1e\n\x0cMoveResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"O\n\x0eRevelioRequest\x12+\n\x0etargetPosition\x18\x01 \x01(\x0b\x32\x13.labyrinth.Position\x12\x10\n\x08tileType\x18\x02 \x01(\t\" \n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\x0f\n\rEmptyResponse2\xd6\x02\n\rLabyrinthGame\x12\x45\n\x10GetLabyrinthInfo\x12\x17.labyrinth.EmptyRequest\x1a\x18.labyrinth.LabyrinthInfo\x12\x43\n\x0fGetPlayerStatus\x12\x17.labyrinth.EmptyRequest\x1a\x17.labyrinth.PlayerStatus\x12?\n\x0cRegisterMove\x12\x16.labyrinth.MoveRequest\x1a\x17.labyrinth.MoveResponse\x12;\n\x07Revelio\x12\x19.labyrinth.RevelioRequest\x1a\x13.labyrinth.Position0\x01\x12;\n\x08\x42ombarda\x12\x13.labyrinth.Position\x1a\x18.labyrinth.EmptyResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'labyrinth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYREQUEST']._serialized_start=30
  _globals['_EMPTYREQUEST']._serialized_end=44
  _globals['_LABYRINTHINFO']._serialized_start=46
  _globals['_LABYRINTHINFO']._serialized_end=92
  _globals['_PLAYERSTATUS']._serialized_start=94
  _globals['_PLAYERSTATUS']._serialized_end=210
  _globals['_MOVEREQUEST']._serialized_start=212
  _globals['_MOVEREQUEST']._serialized_end=244
  _globals['_MOVERESPONSE']._serialized_start=246
  _globals['_MOVERESPONSE']._serialized_end=276
  _globals['_REVELIOREQUEST']._serialized_start=278
  _globals['_REVELIOREQUEST']._serialized_end=357
  _globals['_POSITION']._serialized_start=359
  _globals['_POSITION']._serialized_end=391
  _globals['_EMPTYRESPONSE']._serialized_start=393
  _globals['_EMPTYRESPONSE']._serialized_end=408
  _globals['_LABYRINTHGAME']._serialized_start=411
  _globals['_LABYRINTHGAME']._serialized_end=753
# @@protoc_insertion_point(module_scope)
